### ISSUE TITLE
Corrupted npy file in the base dataset

### ISSUE THREAD

**Issue by HaFred** [EmbodiedGPT/EgoCOT_Dataset#4]
When doing `np.load(~/egocot/EgoCOT/EgoCOT_clear/EGO_10752.npy)`, errors shown as below. Just so you know.
```log
Traceback (most recent call last):
  File "~/egocot/EgoCOT/readnpy.py", line 4, in <module>
    nparr = np.load(p)
  File "~/lib/python3.10/site-packages/numpy/lib/npyio.py", line 456, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "~/lib/python3.10/site-packages/numpy/lib/format.py", line 839, in read_array
    array.shape = shape
ValueError: cannot reshape array of size 1081312 into shape (8,3,224,224)
```

**Comment by WaikeiGum** [comment]
> When doing `np.load(~/egocot/EgoCOT/EgoCOT_clear/EGO_10752.npy)`, errors shown as below. Just so you know.
> 
> ```
> Traceback (most recent call last):
>   File "~/egocot/EgoCOT/readnpy.py", line 4, in <module>
>     nparr = np.load(p)
>   File "~/lib/python3.10/site-packages/numpy/lib/npyio.py", line 456, in load
>     return format.read_array(fid, allow_pickle=allow_pickle,
>   File "~/lib/python3.10/site-packages/numpy/lib/format.py", line 839, in read_array
>     array.shape = shape
> ValueError: cannot reshape array of size 1081312 into shape (8,3,224,224)
> ```

Met the same error. EGO_10752.npy is smaller than the rest.
